version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/nodejs-docs-hello-world
hooks:
  AfterInstall:
    - location: scripts/install_dependencies
      timeout: 1800
  # ApplicationStart:
  #   - location: scripts/start_server.sh
  #     timeout: 360
  # ApplicationStop:
  #   - location: scripts/stop_server.sh
  #     timeout: 360